Description of clearSingleAxis
clearSingleAxis
PURPOSE
clears an individual axis
SYNOPSIS
function clearSingleAxis(axh)
DESCRIPTION
clearSingleAxis clears an individual axis
 Syntax:
       clearSingleAxis(axh)
 Inputs:
       axh - axis handle
 Outputs:
       none
 Example:
       clearSingleAxis(gca)
 Other m-files required:
       clearSingleAxis
 Subfunctions:
       none
 MAT-files required:
       none
 See also: BLOCHUS
 Author: Thomas Hiller
 email: thomas.hiller[at]leibniz-liag.de
 License: GNU GPLv3 (at end)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BLOCHUS_createGridPlots creates the "Plots" grid panel
onCheckPrePolPulse activates / deactivates all control elements needed for
plotResults plots results depending on the chosen settings
SOURCE CODE
function clearSingleAxis(axh)
%clearSingleAxis clears an individual axis
%
% Syntax:
%       clearSingleAxis(axh)
%
% Inputs:
%       axh - axis handle
%
% Outputs:
%       none
%
% Example:
%       clearSingleAxis(gca)
%
% Other m-files required:
%       clearSingleAxis
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: BLOCHUS
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: GNU GPLv3 (at end)
%------------- BEGIN CODE --------------
% get GUI handle
fig = ancestor(axh,'figure','toplevel');
if ~isempty(fig) && strcmp(get(fig,'Tag'),'BLOCHUS')
    % get GUI data
    gui = getappdata(fig,'gui');
    % get the parent of the axis and find possible legends
    parent = get(axh,'Parent');
    lgh = findobj('Type','legend','Parent',parent);
    if ~isempty(lgh)
        delete(lgh);
    end
    % look for specific tags and clear corresponding objects
    ph = findall(axh,'Tag','MarkerLines');
    if ~isempty(ph); set(ph,'HandleVisibility','on'); end
    % clear the axis labels
    xlabel(axh,'');
    ylabel(axh,'');
    zlabel(axh,'');
    % reset axis limits and scale
    grid(axh,'off');
    set(axh,'XLim',[0 1],'YLim',[0 1],'ZLim',[0 1]);
    set(axh,'XScale','lin','YScale','lin','ZScale','lin');
    set(axh,'FontSize',gui.myui.axfontsize);
    % clear the axis itself
    cla(axh);
else
    warndlg({'clearSingleAxis:','There is no figure with the BLOCHUS Tag open.'},...
        'BLOCHUS error');
end
end
%------------- END OF CODE --------------
%% License:
% GNU GPLv3
%
% BLOCHUS
% Copyright (C) 2019 Thomas Hiller
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://www.gnu.org/licenses/>.