Description of minimizePanel
minimizePanel
PURPOSE
handles the minimization/maximization of all box-panels
SYNOPSIS
function minimizePanel(src,~)
DESCRIPTION
minimizePanel handles the minimization/maximization of all box-panels
 Syntax:
       minimizePanel(src)
 Inputs:
       src - handle of the calling object
 Outputs:
       none
 Example:
       minimizePanel(src)
 Other m-files required:
       findParentOfType
 Subfunctions:
       none
 MAT-files required:
       none
 See also: BLOCHUS
 Author: Thomas Hiller
 email: thomas.hiller[at]leibniz-liag.de
 License: GNU GPLv3 (at end)
CROSS-REFERENCE INFORMATION
This function calls:
findParentOfType is a "hack" because Matlab changed the parent-child
onFigureSizeChange fixes an ugly Matlab bug when resizing a box-panel
This function is called by:
BLOCHUS_createGUI controls the creation of all GUI elements
SOURCE CODE
function minimizePanel(src,~)
%minimizePanel handles the minimization/maximization of all box-panels
%
% Syntax:
%       minimizePanel(src)
%
% Inputs:
%       src - handle of the calling object
%
% Outputs:
%       none
%
% Example:
%       minimizePanel(src)
%
% Other m-files required:
%       findParentOfType
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: BLOCHUS
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: GNU GPLv3 (at end)
%------------- BEGIN CODE --------------
%% get GUI handle and data
fig = ancestor(src,'figure','toplevel');
gui = getappdata(fig,'gui');
% get the corresponding box-panel to be minimized / maximized
panel = findParentOfType(src,'uix.BoxPanel');
% panel title
paneltitle = get(panel,'Title');
% check if panel is minimized (true)
isminimized = get(panel,'Minimized');
% minimized height (default value for all box-panels)
pheightmin = 22;
% default heights
def_heights = gui.myui.heights;
if ~isempty(fig) && strcmp(get(fig,'Tag'),'BLOCHUS')
    panel_1 = 'Basics';
    panel_2 = 'Pre-polarization switch-off';
    panel_3 = 'Pulse';
    switch paneltitle
        case panel_1
            id = 1;
        case panel_2
            id = 2;
        case panel_3
            id = 3;
        otherwise
            helpdlg({'function: minimizePanel',...
                'Something is utterly wrong.'},'Info');
    end
    switch paneltitle
        case {panel_1,panel_2,panel_3}
            % all heights of the left panels
            heights = get(gui.panels.main,'Heights');
            % default height of this panel
            pheight = def_heights(2,id);
            if isminimized % maximize panel
                heights(id) = pheight;
                set(gui.panels.main,'Heights',heights);
                set(panel,'Minimized',false);
            else % minimize panel
                heights(id) = pheightmin;
                set(gui.panels.main,'Heights',heights);
                set(panel,'Minimized',true)
            end
            onFigureSizeChange(fig);
        otherwise
            helpdlg({'function: minimizePanel',...
                'Something is utterly wrong.'},'Info');
    end
else
    warndlg({'minimizePanel:','There is no figure with the BLOCHUS Tag open.'},...
        'BLOCHUS error');
end
% update GUI data
setappdata(fig,'gui',gui);
end
%------------- END OF CODE --------------
%% License:
% GNU GPLv3
%
% BLOCHUS
% Copyright (C) 2019 Thomas Hiller
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://www.gnu.org/licenses/>.